server.port=9908

spring.profiles.active=promodiscount

spring.devtools.restart.enabled=false

server.servlet.context-path=/pd-svc

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always